apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: container-workshop # cluster name
  region: us-east-1 # cluster region
  version: "1.25" # K8s version of cluster


managedNodeGroups:
  - name: node-group-01  # name of node group
    instanceType: t2.small # desired instance-type of instances in node-group
    desiredCapacity: 1  # desired number of instances of node-group
    minSize: 1
    maxSize: 2
    ssh:
      allow: false
    volumeSize: 20
    volumeEncrypted: true

